version: '3.4'

services:
  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    ports:
        - 62341:8080 

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    ports:
        - 62342:8080 

